# Generated by Django 3.2 on 2023-01-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230103_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='bear',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
